### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by LyonelB** [mickaelmonsieur/openob-gui#3]
Bonjour,

Avec OpenOB-GUI installé sur un Raspberry Pi 3 et Raspbian Jessie, j'ai l'erreur suivante en mode instreamer :

```
File "build/bdist.linux-armv7l/egg/openob/rtp/tx.py", line 49, in __init__
    self.encoder.set_property('frame-size', self.link_config.opus_framesize)
  File "build/bdist.linux-armv7l/egg/openob/link_config.py", line 75, in __getattr__
    return self.get(key)
  File "build/bdist.linux-armv7l/egg/openob/link_config.py", line 62, in get
    value = int(value)
TypeError: int() argument must be a string or a number, not 'NoneType'
2017-09-14 15:11:02,912 - openob.node.emetteur.link.None - INFO - Starting up transmitter
2017-09-14 15:11:02,926 - openob.node.emetteur.link.None.tx - INFO - Creating RTP transmission pipeline
2017-09-14 15:11:02,934 - openob.node.emetteur.link.None - ERROR - Transmitter crashed for some reason! Restarting...
Traceback (most recent call last):
  File "build/bdist.linux-armv7l/egg/openob/node.py", line 47, in run_link
    transmitter = RTPTransmitter(self.node_name, link_config, audio_interface)
  File "build/bdist.linux-armv7l/egg/openob/rtp/tx.py", line 49, in __init__
    self.encoder.set_property('frame-size', self.link_config.opus_framesize)
  File "build/bdist.linux-armv7l/egg/openob/link_config.py", line 75, in __getattr__
    return self.get(key)
  File "build/bdist.linux-armv7l/egg/openob/link_config.py", line 62, in get
    value = int(value)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by EduardoRicobaldi** [comment]
Add in instreamer.py missing defaults.
```
link_config.set("opus_framesize", "20")
link_config.set("opus_complexity", "9")
link_config.set("opus_loss_expectation", "0")
link_config.set("jitter_buffer", "40")
link_config.set("opus_dtx", False)
link_config.set("opus_fec", True) 
```
In outstreamer.py add too
```
link_config.set("jitter_buffer", "40") 
```

**Comment by mickaelmonsieur** [comment]
# ⚠️ This project is no longer maintained

**openob-gui is an old Debian 8 / Raspbian Jessie project and is no longer maintained.**

If you are looking for a modern Raspberry Pi IP audio codec for broadcast use, please use **OpenSonix** instead:

# 👉 [OpenSonix — open-source Raspberry Pi IP audio codec](https://github.com/mickaelmonsieur/OpenSonix)

OpenSonix is the successor project: Raspberry Pi OS Bookworm, SIP/OPUS, web UI, real-time VU meters, Sender/Receiver modes, network configuration, diagnostics and image-based releases.

---

Mickael
